name: Validate Next JS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
    # - run: yarn test
